// ============================================================
// CityWatcher - Municipal Contact Information Database
// Generated from research data: 24 February 2026
// Source: Official .gov.za websites
// ============================================================

export interface MunicipalContact {
  id: string;
  serviceName: string;
  department: string;
  region: 'KZN' | 'Western Cape' | 'Gauteng';
  municipality: string;
  phone: string;
  tollFree?: string;
  email?: string;
  smsWhatsApp?: string;
  hours: string;
  is24Hour: boolean;
  website?: string;
  address?: string;
  languages: string[];
  category: 'emergency' | 'municipal' | 'reporting' | 'utility';
  priority: 'high' | 'medium' | 'low';
}

export const NATIONAL_EMERGENCY = {
  mobile: '112',
  saps: '10111',
  ambulance: '10177',
};

export const MUNICIPAL_CONTACTS: MunicipalContact[] = [
  // ============================================================
  // REGION 1: KwaZulu-Natal
  // ============================================================
  
  // eThekwini Municipality (Durban)
  {
    id: 'eth-emergency-001',
    serviceName: 'eThekwini Emergency Response',
    department: 'Public Safety & Emergency Services',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '031 361 0000',
    hours: '24 hours',
    is24Hour: true,
    website: 'https://www.durban.gov.za/page/public-safety-emergency-services',
    address: 'City Hall, 263 Dr Pixley Ka Seme Street, Durban 4001',
    languages: ['English', 'Zulu'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'eth-customer-001',
    serviceName: 'Sizakala Customer Services',
    department: 'Customer Services',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '031 311 1111',
    tollFree: '080 311 1111',
    email: 'sizakala@durban.gov.za',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.durban.gov.za/page/sizakala-customer-services',
    address: '166 KE Masinga Road, Durban',
    languages: ['English', 'Zulu'],
    category: 'municipal',
    priority: 'high',
  },
  {
    id: 'eth-electricity-001',
    serviceName: 'Electricity Faults & Power Outages',
    department: 'Electricity',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '080 311 1111',
    tollFree: '080 311 1111',
    email: 'electricity.faults@durban.gov.za',
    smsWhatsApp: '076 791 2449',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.durban.gov.za/page/electricity',
    languages: ['English', 'Zulu'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'eth-water-001',
    serviceName: 'Water Leaks & Sanitation',
    department: 'Water & Sanitation',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '080 311 1111',
    tollFree: '080 311 1111',
    smsWhatsApp: '073 148 3477',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.durban.gov.za',
    languages: ['English', 'Zulu'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'eth-waste-001',
    serviceName: 'Waste Management & Illegal Dumping',
    department: 'Cleansing & Solid Waste',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '080 311 1111',
    tollFree: '080 311 1111',
    hours: '24/7 via Sizakala',
    is24Hour: false,
    website: 'https://www.durban.gov.za/page/cleansing-and-solid-waste',
    languages: ['English', 'Zulu'],
    category: 'reporting',
    priority: 'medium',
  },
  {
    id: 'eth-roads-001',
    serviceName: 'Potholes / Roads / Street Lights',
    department: 'Transportation',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '080 311 1111',
    tollFree: '080 311 1111',
    hours: '24/7',
    is24Hour: false,
    website: 'https://www.durban.gov.za/page/transportation',
    languages: ['English', 'Zulu'],
    category: 'reporting',
    priority: 'medium',
  },
  {
    id: 'eth-beach-001',
    serviceName: 'Beach Safety / Lifeguards',
    department: 'Public Safety',
    region: 'KZN',
    municipality: 'eThekwini (Durban)',
    phone: '031 361 0000',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.durban.gov.za/page/public-safety-emergency-services',
    languages: ['English', 'Zulu'],
    category: 'emergency',
    priority: 'high',
  },

  // KwaDukuza Municipality
  {
    id: 'kwd-fire-001',
    serviceName: 'Fire & Emergency Services',
    department: 'Community Safety',
    region: 'KZN',
    municipality: 'KwaDukuza (Stanger)',
    phone: '032 437 5515',
    email: 'nonhlanhlam@kwadukuza.gov.za',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.kwadukuza.gov.za',
    address: '2 Industria Crescent, KwaDukuza',
    languages: ['English', 'Zulu'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'kwd-disaster-001',
    serviceName: 'Disaster Management',
    department: 'Community Safety',
    region: 'KZN',
    municipality: 'KwaDukuza (Stanger)',
    phone: '032 437 5502',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.kwadukuza.gov.za',
    languages: ['English', 'Zulu'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'kwd-main-001',
    serviceName: 'Main Switchboard & Customer Care',
    department: 'Administration',
    region: 'KZN',
    municipality: 'KwaDukuza (Stanger)',
    phone: '032 437 5000',
    email: 'enquiries@kwadukuza.gov.za',
    hours: 'Mon-Fri 08:00-16:30',
    is24Hour: false,
    website: 'https://www.kwadukuza.gov.za',
    languages: ['English', 'Zulu'],
    category: 'municipal',
    priority: 'medium',
  },
  {
    id: 'kwd-electricity-001',
    serviceName: 'Electricity Faults',
    department: 'Electricity',
    region: 'KZN',
    municipality: 'KwaDukuza (Stanger)',
    phone: '032 437 5077',
    email: 'kdmcontrol@kwadukuza.gov.za',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.kwadukuza.gov.za',
    languages: ['English', 'Zulu'],
    category: 'utility',
    priority: 'high',
  },

  // iLembe District
  {
    id: 'ilm-main-001',
    serviceName: 'District Main Call Centre',
    department: 'Administration',
    region: 'KZN',
    municipality: 'iLembe District',
    phone: '032 437 9300',
    email: 'call.centre@ilembe.gov.za',
    hours: 'Mon-Fri 07:30-16:30',
    is24Hour: false,
    website: 'https://ilembe.gov.za',
    languages: ['English', 'Zulu'],
    category: 'municipal',
    priority: 'medium',
  },
  {
    id: 'ilm-water-001',
    serviceName: 'Water & Sanitation Call Centre',
    department: 'Water Services',
    region: 'KZN',
    municipality: 'iLembe District',
    phone: '032 437 9427',
    hours: 'Mon-Fri',
    is24Hour: false,
    website: 'https://ilembe.gov.za',
    languages: ['English', 'Zulu'],
    category: 'utility',
    priority: 'medium',
  },

  // ============================================================
  // REGION 2: Western Cape
  // ============================================================

  // City of Cape Town
  {
    id: 'cpt-emergency-001',
    serviceName: 'Public Emergency Communication Centre',
    department: 'Public Safety',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '021 480 7700',
    tollFree: '107',
    hours: '24 hours',
    is24Hour: true,
    website: 'https://www.capetown.gov.za/City-Connect/Report/Report-an-emergency',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'cpt-contact-001',
    serviceName: 'City Contact Centre',
    department: 'Customer Care',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '0860 103 089',
    tollFree: '0860 103 089',
    email: 'contact.us@capetown.gov.za',
    hours: '24/7 for emergencies',
    is24Hour: false,
    website: 'https://www.capetown.gov.za/General/Contact-us',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'municipal',
    priority: 'high',
  },
  {
    id: 'cpt-water-001',
    serviceName: 'Water & Sanitation',
    department: 'Water & Sanitation',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '0860 103 089',
    email: 'water@capetown.gov.za',
    smsWhatsApp: 'WhatsApp: 060 018 1505 | SMS: 31373',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.capetown.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'cpt-electricity-001',
    serviceName: 'Electricity',
    department: 'Electricity',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '0860 103 089',
    email: 'power@capetown.gov.za',
    smsWhatsApp: 'SMS: 31220',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.capetown.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'cpt-roads-001',
    serviceName: 'Roads / Potholes / Stormwater',
    department: 'Transport',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '0800 656 463',
    tollFree: '0800 656 463',
    email: 'Transport.Info@capetown.gov.za',
    hours: '24/7',
    is24Hour: false,
    website: 'https://www.capetown.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'reporting',
    priority: 'medium',
  },
  {
    id: 'cpt-waste-001',
    serviceName: 'Waste / Illegal Dumping',
    department: 'Solid Waste',
    region: 'Western Cape',
    municipality: 'City of Cape Town',
    phone: '0860 103 089',
    email: 'wastewise@capetown.gov.za',
    hours: 'via Contact Centre',
    is24Hour: false,
    website: 'https://www.capetown.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'reporting',
    priority: 'medium',
  },

  // Stellenbosch
  {
    id: 'stb-emergency-001',
    serviceName: '24-Hour Municipal Emergency',
    department: 'Public Safety',
    region: 'Western Cape',
    municipality: 'Stellenbosch',
    phone: '021 808 8890',
    smsWhatsApp: '076 951 0768 (general) / 079 622 4722 (law)',
    hours: '24 hours',
    is24Hour: true,
    website: 'https://stellenbosch.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'stb-main-001',
    serviceName: 'Main Switchboard',
    department: 'Administration',
    region: 'Western Cape',
    municipality: 'Stellenbosch',
    phone: '021 808 8111',
    hours: 'Mon-Fri 08:00-16:30',
    is24Hour: false,
    website: 'https://stellenbosch.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'municipal',
    priority: 'medium',
  },

  // Drakenstein
  {
    id: 'drk-customer-001',
    serviceName: 'Customer Care & Emergencies',
    department: 'Customer Care',
    region: 'Western Cape',
    municipality: 'Drakenstein (Paarl)',
    phone: '021 807 4500',
    tollFree: '080 131 3553',
    email: 'customercare@drakenstein.gov.za',
    hours: 'Mon-Fri + after-hours 021 807 4665',
    is24Hour: false,
    website: 'https://www.drakenstein.gov.za',
    languages: ['English', 'Afrikaans'],
    category: 'municipal',
    priority: 'medium',
  },

  // George
  {
    id: 'geo-emergency-001',
    serviceName: 'Municipal Emergencies / After-Hours',
    department: 'Administration',
    region: 'Western Cape',
    municipality: 'George',
    phone: '044 801 6300',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.george.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'geo-fire-001',
    serviceName: 'Fire Department',
    department: 'Fire & Rescue',
    region: 'Western Cape',
    municipality: 'George',
    phone: '044 801 6311',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.george.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'geo-disaster-001',
    serviceName: 'Disaster Management',
    department: 'Disaster Management',
    region: 'Western Cape',
    municipality: 'George',
    phone: '087 152 9999',
    tollFree: '087 152 9999',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.george.gov.za',
    languages: ['English', 'Afrikaans', 'Xhosa'],
    category: 'emergency',
    priority: 'high',
  },

  // Overstrand
  {
    id: 'ovr-emergency-001',
    serviceName: 'Municipal Services Emergencies',
    department: 'Administration',
    region: 'Western Cape',
    municipality: 'Overstrand (Hermanus)',
    phone: '028 313 8111',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.overstrand.gov.za',
    languages: ['English', 'Afrikaans'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'ovr-fire-001',
    serviceName: 'Fire & Rescue',
    department: 'Fire & Rescue',
    region: 'Western Cape',
    municipality: 'Overstrand (Hermanus)',
    phone: '028 312 2400',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.overstrand.gov.za',
    languages: ['English', 'Afrikaans'],
    category: 'emergency',
    priority: 'high',
  },

  // ============================================================
  // REGION 3: Gauteng
  // ============================================================

  // City of Johannesburg
  {
    id: 'jhb-emergency-001',
    serviceName: 'Emergency Connect',
    department: 'Emergency Management',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '011 375 5911',
    hours: '24 hours',
    is24Hour: true,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'jhb-connect-001',
    serviceName: 'Joburg Connect Call Centre',
    department: 'Customer Services',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '0860 562 874',
    tollFree: '0860 562 874',
    email: 'joburgconnect@joburg.org.za',
    hours: '24/7',
    is24Hour: false,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'municipal',
    priority: 'high',
  },
  {
    id: 'jhb-power-001',
    serviceName: 'City Power (Electricity)',
    department: 'Electricity',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '011 490 7000',
    tollFree: '0800 202 925',
    hours: '24/7 faults',
    is24Hour: true,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'jhb-water-001',
    serviceName: 'Johannesburg Water (Leaks)',
    department: 'Water',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '011 688 1699',
    hours: '24/7',
    is24Hour: true,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'utility',
    priority: 'high',
  },
  {
    id: 'jhb-waste-001',
    serviceName: 'Pikitup (Waste & Illegal Dumping)',
    department: 'Waste Management',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '010 055 5990',
    smsWhatsApp: '082 779 1361',
    hours: 'via Joburg Connect',
    is24Hour: false,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'reporting',
    priority: 'medium',
  },
  {
    id: 'jhb-roads-001',
    serviceName: 'JRA (Roads / Potholes / Street Lights)',
    department: 'Roads Agency',
    region: 'Gauteng',
    municipality: 'City of Johannesburg',
    phone: '0860 562 874',
    hours: 'via Joburg Connect',
    is24Hour: false,
    website: 'https://joburg.org.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'reporting',
    priority: 'medium',
  },

  // Ekurhuleni
  {
    id: 'eku-emergency-001',
    serviceName: 'Life-Threatening Emergencies',
    department: 'Public Safety',
    region: 'Gauteng',
    municipality: 'Ekurhuleni',
    phone: '011 458 0911',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.ekurhuleni.gov.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'eku-call-001',
    serviceName: 'Municipal Call Centre',
    department: 'Customer Services',
    region: 'Gauteng',
    municipality: 'Ekurhuleni',
    phone: '0860 543 000',
    tollFree: '0860 543 000',
    email: 'call.centre@ekurhuleni.gov.za',
    hours: '24/7',
    is24Hour: false,
    website: 'https://www.ekurhuleni.gov.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'municipal',
    priority: 'high',
  },

  // City of Tshwane
  {
    id: 'tsw-emergency-001',
    serviceName: 'Tshwane Emergency Services',
    department: 'Emergency Management',
    region: 'Gauteng',
    municipality: 'City of Tshwane (Pretoria)',
    phone: '012 358 6300',
    tollFree: '107',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.tshwane.gov.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'tsw-metro-001',
    serviceName: 'Tshwane Metro Police',
    department: 'Metro Police',
    region: 'Gauteng',
    municipality: 'City of Tshwane (Pretoria)',
    phone: '012 358 7095',
    hours: '24/7',
    is24Hour: true,
    website: 'https://www.tshwane.gov.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'emergency',
    priority: 'high',
  },
  {
    id: 'tsw-contact-001',
    serviceName: 'Customer Contact Centre',
    department: 'Customer Services',
    region: 'Gauteng',
    municipality: 'City of Tshwane (Pretoria)',
    phone: '012 358 9999',
    tollFree: '080 111 1556',
    smsWhatsApp: '087 153 1001',
    hours: '24/7',
    is24Hour: false,
    website: 'https://www.tshwane.gov.za',
    languages: ['English', 'Afrikaans', 'Zulu', 'Sotho'],
    category: 'municipal',
    priority: 'high',
  },
];

// Helper functions
export const getContactsByRegion = (region: string) => {
  return MUNICIPAL_CONTACTS.filter(contact => contact.region === region);
};

export const getContactsByMunicipality = (municipality: string) => {
  return MUNICIPAL_CONTACTS.filter(contact => 
    contact.municipality.toLowerCase().includes(municipality.toLowerCase())
  );
};

export const getEmergencyContacts = () => {
  return MUNICIPAL_CONTACTS.filter(contact => contact.category === 'emergency');
};

export const get24HourContacts = () => {
  return MUNICIPAL_CONTACTS.filter(contact => contact.is24Hour);
};

export const searchContacts = (query: string) => {
  const lowerQuery = query.toLowerCase();
  return MUNICIPAL_CONTACTS.filter(contact =>
    contact.serviceName.toLowerCase().includes(lowerQuery) ||
    contact.department.toLowerCase().includes(lowerQuery) ||
    contact.municipality.toLowerCase().includes(lowerQuery)
  );
};
